### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by vr8hub** [brplatinum/james-branch-cabell_domnei#2]
- [x] In instances where there is a paragraph with italics and the xml:lang is on the paragraph, it should be on the italics. See, e.g., the French paragraph in the foreword, but I might have seen one or two others?
- [x] The opening quote mark in The Argument (epigraph-4) is a closing quote, not an opening one.
- [x] The M.'s in the afterword need abbr tags.
- [x] We don't italicize foreign words that are found in Merriam-Webster, so the "domnei's" in the various places should have their italics removed. However, the uppercase Domnei's, at least in the preface, are referring to the book, so they should have book semantics on them.
- [x] Are all of the verse quote full poems, or intended to be (I didn't research, but I'm guessing they're fictional as well)? Either way, in case any are not full poems, they should be z3998:verse instead of z3998:poem (see [7.5.6.1](https://standardebooks.org/manual/1.5.0/single-page#7.5.6.1) of the manual).
- [x] I don't think I've ever encountered them in ordinals before, but I'm guessing we should tag the roman numerals in Nouvelles Françoises en prose du XIVe, etc. Just the number, not the trailing e.

**Comment by reecetwhite** [comment]
I believe the poems are fictional and I'm assuming they're all full poems, but I'm not sure how to tell.

**Comment by vr8hub** [comment]
For fictional or not, just do a web search on a line or two and see if it shows up anywhere but in Domnai. :)

If they are fictional, it’s probably safe to treat them all as full poems as you’re doing.

**Comment by vr8hub** [comment]
I should clarify—I don't think you need to check every poem. If a couple are fictional, the odds are huge they all are, especially given everything else about the work.
