### ISSUE TITLE
Afterword

### ISSUE THREAD

**Issue by vr8hub** [brplatinum/james-branch-cabell_domnei#4]
- [x] I'm not sure about the paragraph numbers in the Afterword. They don't seem to serve a purpose, and we would usually cut them. If we do include them, we would probably make the first one 1, and make each their own section so that the numbers would be headers. I'll ask Alex about it on list.
- [x] The break before the last paragraph in the Afterword should be formatted with an <hr/> just like the other breaks in the book.

**Comment by vr8hub** [comment]
Oops, I didn't quote the `<hr>`. I forgot to check the preview, my bad.

**Comment by vr8hub** [comment]
Alex has spoken. You're going to want to make sub-sections for each of the four sections. So, just another `<section id="afterword-X">` where X is 1-4, and then of course a matching `</section>` at the end of the section. Then you can have put an h# header in them, just like you have on the top-level sections in each chapter. The h# will be one more than the afterward itself. You can leave the header off of the first one since it doesn't have one. You'll need to regen the ToC when you're finished.

**Comment by reecetwhite** [comment]
Hey Vince, could you please check my latest commit and let me know if this is what you mean? The main thing I'm wondering is in the ToC the subsections are English numerals not Roman numerals, is this fine?

**Comment by vr8hub** [comment]
The sections look perfect.

Good question on the numbers; I can go either way, but I think Alex will want them roman. (Which is consistent with the chapter numbers; both decimal in the source, both roman in our edition.)

However, the headers need to follow the same semantics as the main headers. See section [7.2.9](https://standardebooks.org/manual/1.6.0/single-page#7.2.9) of the manual for details, but essentially what you did for the chapter headers, except here you don't have the actual title, just the ordinal.
